### ISSUE TITLE
Invalid input causes endless key generation loop

### ISSUE THREAD

**Issue by gunnaraas** [PGBlitz/PGBlitz.com#849]
**Describe the bug**
When creating service keys for PG Blitz, entering in an invalid selection for number of keys causes the program to keep looping and creating new keys until disconnecting from the SSH session.

**To Reproduce**
1. Go to 'PG Blitz Key Generation'
2. Click on '[3] Create Service Keys'
3. Enter a value that is not a listed option

**Expected behavior**
Entering an invalid selection should throw an error message, not prompt an endless loop of key generation.

**Environment**
  * Operating System: Ubuntu [18.04]
  * Plexguide Version: 8.4.2 [Stable]
  * Plexguide Server Type: [Remote VPS or VM]
  * Plexguide Edition: [GCE]
  * Plexguide Mount System: [PlexDrive/PGBlitz/ST2]
  * Using Traefik: [Yes]
  * Domain DNS Provider:[CloudFlare]

**Comment by Admin9705** [comment]
ya gonna work it in an pgclone rewrite update for 8.6, but will keep this as a reminder.

**Comment by Admin9705** [comment]
![image](https://user-images.githubusercontent.com/24727006/54076916-07c2d680-427f-11e9-8784-d3e47f77a623.png)

resolved, fixed in 8.6; people type custom; complete rewrite.  8.6 beta should be out soon.
