### ISSUE TITLE
[8.4.7] Update post install does not respect pgui disabled value

### ISSUE THREAD

**Issue by azerial** [PGBlitz/PGBlitz.com#852]
**impact: low User annoyance**

**Experienced**: On my plexguide install, i have disabled pgui. When i ran pgupdate to get to the latest version, plexguide redeployed pgui as part of the post update process, ignoring the fact that pgui had been disabled.

**Expected**: If pgui is disabled, it should not be deployed after an update. 

**Repro**:
1. Install Plexguide to an old version  
2. Disable pgui in the settings menu  
3. Verify that pgui is disabled  
4. Exit plexguide and run `sudo pgupdate`  
5. Update to the latest version  
6. After update is complete, run `sudo plexguide`  
7. Observe that plexguide installs pgui  
8. Navigate to the plexguide settings and observe PG UI is still disabled  
9. Navigate to portainer or run `sudo docker ps` and observe pgui is running.   

Logs (because i couldn't get github to format it nicely): 
https://pastebin.com/raw/1e1FD8yu

**Comment by Admin9705** [comment]
it's all good, i'll check into it. thanks for the heads up

**Comment by Admin9705** [comment]
checking this still for 8.5

**Comment by Admin9705** [comment]
ya it disables it fine.
