### ISSUE TITLE
PG 10 Release Roadmap

### ISSUE THREAD

**Issue by robertbaker** [PGBlitz/PGBlitz.com#855]
PG 10 will break everything! Seriously. This is a WIP roadmap of what we want PG 10 to be.

This may enable multi-user environments, but needs to be proven. This will solve the custom exclusions we must add to pgclone as the community adds custom downloaders. This also just considates everything down to be under 1 folder (by default)

This new structure will consolidate

# New directory structure and layout:
- `$InstallLocation` = `~/pg` by default
- `$logLocation` =  `$installLocation/logs`
- `$dataLocation` = `$InstallLocation/pgdata`
- `$incompleteLocation` = `$InstallLocation/pgdata/local/incomplete`
- `$transcodeLocation` = `$InstallLocation/transcodes`
- `$appdataLocation` = `$InstallLocation/appdata`
-  Move mostly everything under `/opt` to `$InstallLocation/{coreapps,communityapps,core,pgui,pgstage,pgvault/etc}`
- custom bins will live under `$InstallLocation/bin` and be linked?
- custom vars will live under `$InstallLocation/config` (or $InstallLocation/vars?)

* Move `/mnt/unionfs` to `$dataLocation/pgunion`
* Move library category folders under `/mnt/unionfs` to `$/pgunion/media/{category} ` (d/tdrive:/media/category)
* Move `/mnt/unionfs/plexguide`(this was really pgvault data) to `$InstallLocation/pgdata/pgunion/backups` (backup/appdata, backup/keys, etc)
* drop `/mnt/incomplete` and `/mnt/downloads`
* `/mnt/downloads/{downloader}` -> `$incompleteLocation/{{downloader}}` (change move/blitz scripts to exclude just `$incompleteLocation/incomplete`, all downloaders and video processing needs to happen under this folder.
 `/mnt/downloads/category` -> `$dataLocation/local/complete/media/{category}`
* `/opt/transcodes` to `$transcodeLocation`

rclone mountpoints:
`$dataLocation/remote/{tdrive/gdrive/tcrypt/gcrypt}`

mergerfs (aka `$dataLocation/pgunion` ) will merge together `$dataLocation/local/complete` and `$dataLocation/local/upload` We will try to drop the move and pgblitz folders in favor just 1 upload folder.

Change menus and settings to go with new structure.
ability to set the new vars as listed above

So by the end of this /mnt and /opt, /var/plexguide/ and custom bins under /bin  no longer exist.

**Comment by robertbaker** [comment]
@Admin9705 
@stephenc87 let me know what you think?

**Comment by stephenc87** [comment]
I like what I see already, security would be improved and the increase use of variables makes so many things easier to manage
The layout bugs me a little, could improve the structure inside $InstallLocation for example making use of $InstallLocation/etc $InstallLocation/var/log and $InstallLocation/mnt will help keep things tidy and make it easier to debug and make packages for
$InstallLocation/opt would prove great for power users who want to test their own scripts with PG

Will the next release be mostly a rewrite? It's certainly due soon..... but when?

**Comment by stephenc87** [comment]
Also, it would be appreciated if I could be unbanned from the forums/discord

**Comment by robertbaker** [comment]
I like the structure I set forth and dislike var /etc /mnt /etc.

The layout I'm proposing is simple and makes more sense to people unfamiliar with the linux layout. I personally find organizing stuff by `domain/module/feature` increases maintainability and decreases movement among directory trees.

There isn't going to be a rewrite AFAIK.....What would a rewrite accomplish, refactoring the code in phases is always a better approach.

This layout may never happen and don't plan on doing this for a while. It would highly depend on making arr and plex upgrade scripts to modify the dbs.

I'm less concerned about niche scope creep.

**Comment by Admin9705** [comment]
lol skipping 9 haha j/k like windows 10?

**Comment by stephenc87** [comment]
Did I say something wrong?

**Comment by Admin9705** [comment]
lets close this and put on the discord or forums :D
