### ISSUE TITLE
Current installer bug

### ISSUE THREAD

**Issue by Chudz** [PGBlitz/PGBlitz.com#867]
Current install errors out at the very start, this happens just after you type `sudo plexguide` for the first time to start the install.

`TASK [Cloning PlexGuide] *******************************************************
Monday 25 February 2019  01:07:17 +0100 (0:00:00.060)       0:00:00.060 *******
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force v8", "msg": "Failed to checkout v8", "rc": 1, "stderr": "error: pathspec 'v8' did not match any file(s) known to git.\n", "stderr_lines": ["error: pathspec 'v8' did not match any file(s) known to git."], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/opt/plexguide/menu/pgstage/pgstage.retry`

**Comment by Admin9705** [comment]
ya checking

**Comment by Admin9705** [comment]
fixed
