### ISSUE TITLE
PyYAMLsh: 48: ansible-playbook: not found

### ISSUE THREAD

**Issue by ruCyberPoison** [PGBlitz/PGBlitz.com#870]
**Describe the bug**
The bug doesn't allow me to install clearly the pblitz i followed method 2 and method 1 same issue on PyYAMLsh said `_48:ansible-playbook: not found_` and i still there..

**To Reproduce**
Just follow the tutorial gived on the pblitz forum 
and type the method 2 or 1 

**What is affected by this bug?**
PyYAMLsh: 48: ansible-playbook: not found
**When does this occur?**
when installing the pgblitz

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [18.04]

**Comment by MrDoobPG** [comment]
Please try this one 

apt-get install sudo && sudo rm -rf /opt/plexguide && sudo rm -rf /var/plexguide && sudo apt install curl -y && curl -s https://raw.githubusercontent.com/PGBlitz/Install/v8.5/install.sh | sudo -H sh

**Comment by Admin9705** [comment]
nobody else is reporting. basically, ansible is not installing and might be your provider/os

**Comment by MrDoobPG** [comment]
No respone 
I closed now
