### ISSUE TITLE
Failing Health check?

### ISSUE THREAD

**Issue by Generalnoob** [PGBlitz/PGBlitz.com#871]
**Describe the bug**
Hi there I'm trying to get your awesome app to run but its not going passed the health check could you please let me know what I', doing wrong please.

**To Reproduce**
`ENV	
TRANSMISSION_WEB_HOME	/config/webui-theme
CREATE_TUN_DEVICE	true
OPENVPN_PASSWORD	*********
TRANSMISSION_BLOCKLIST_ENABLED	true
TRANSMISSION_BLOCKLIST_URL	http://john.bitsurge.net/public/biglist.p2p.gz
WEBPROXY_ENABLED	true
OPENVPN_USERNAME	************
WEBPROXY_PORT	8888
TRANSMISSION_INCOMPLETE_DIR	/mnt/incomplete/stransmission
TRANSMISSION_HOME	/config/home
PGID	1000
LOCAL_NETWORK	172.19.0.0/24 ###tried original no change###
TRANSMISSION_WATCH_DIR_ENABLED	false
TRANSMISSION_DOWNLOAD_DIR	/mnt/downloads/stransmission
TRANSMISSION_RPC_PORT	9091
TRANSMISSION_WEB_UI	transmission-web-control
TRANSMISSION_WATCH_DIR	/config/watch
OPENVPN_OPTS	--auth-user-pass --auth-nocache --inactive 3600 --ping 10 --ping-exit 60
TRANSMISSION_DHT_ENABLED	false
PUID	1000
OPENVPN_PROVIDER	NORDVPN
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GLOBAL_APPLY_PERMISSIONS	true
TRANSMISSION_ALT_SPEED_DOWN	50
TRANSMISSION_ALT_SPEED_ENABLED	false
TRANSMISSION_ALT_SPEED_TIME_BEGIN	540
TRANSMISSION_ALT_SPEED_TIME_DAY	127
TRANSMISSION_ALT_SPEED_TIME_ENABLED	false
TRANSMISSION_ALT_SPEED_TIME_END	1020
TRANSMISSION_ALT_SPEED_UP	50
TRANSMISSION_BIND_ADDRESS_IPV4	0.0.0.0
TRANSMISSION_BIND_ADDRESS_IPV6	::
TRANSMISSION_CACHE_SIZE_MB	4
TRANSMISSION_DOWNLOAD_LIMIT	100
TRANSMISSION_DOWNLOAD_LIMIT_ENABLED	0
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED	true
TRANSMISSION_DOWNLOAD_QUEUE_SIZE	5
TRANSMISSION_ENCRYPTION	1
TRANSMISSION_IDLE_SEEDING_LIMIT	30
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED	false
TRANSMISSION_INCOMPLETE_DIR_ENABLED	true
TRANSMISSION_LPD_ENABLED	false
TRANSMISSION_MAX_PEERS_GLOBAL	200
TRANSMISSION_MESSAGE_LEVEL	2
TRANSMISSION_PEER_ID_TTL_HOURS	6
TRANSMISSION_PEER_LIMIT_GLOBAL	200
TRANSMISSION_PEER_LIMIT_PER_TORRENT	50
TRANSMISSION_PEER_PORT	51413
TRANSMISSION_PEER_PORT_RANDOM_HIGH	65535
TRANSMISSION_PEER_PORT_RANDOM_LOW	49152
TRANSMISSION_PEER_PORT_RANDOM_ON_START	false
TRANSMISSION_PEER_SOCKET_TOS	default
TRANSMISSION_PEX_ENABLED	true
TRANSMISSION_PORT_FORWARDING_ENABLED	false
TRANSMISSION_PREALLOCATION	1
TRANSMISSION_PREFETCH_ENABLED	1
TRANSMISSION_QUEUE_STALLED_ENABLED	true
TRANSMISSION_QUEUE_STALLED_MINUTES	30
TRANSMISSION_RATIO_LIMIT	2
TRANSMISSION_RATIO_LIMIT_ENABLED	false
TRANSMISSION_RENAME_PARTIAL_FILES	true
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED	false
TRANSMISSION_RPC_BIND_ADDRESS	0.0.0.0
TRANSMISSION_RPC_ENABLED	true
TRANSMISSION_RPC_HOST_WHITELIST_ENABLED	false
TRANSMISSION_RPC_PASSWORD	password
TRANSMISSION_RPC_URL	/transmission/
TRANSMISSION_RPC_USERNAME	username
TRANSMISSION_RPC_WHITELIST	127.0.0.1
TRANSMISSION_RPC_WHITELIST_ENABLED	false
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED	true
TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED	false
TRANSMISSION_SEED_QUEUE_ENABLED	false
TRANSMISSION_SEED_QUEUE_SIZE	10
TRANSMISSION_SPEED_LIMIT_DOWN	100
TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED	false
TRANSMISSION_SPEED_LIMIT_UP	100
TRANSMISSION_SPEED_LIMIT_UP_ENABLED	false
TRANSMISSION_START_ADDED_TORRENTS	true
TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES	false
TRANSMISSION_UMASK	2
TRANSMISSION_UPLOAD_LIMIT	100
TRANSMISSION_UPLOAD_LIMIT_ENABLED	0
TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT	14
TRANSMISSION_UTP_ENABLED	true
TRANSMISSION_WATCH_DIR_FORCE_GENERIC	false
ENABLE_UFW	false
UFW_ALLOW_GW_NET	false
UFW_DISABLE_IPTABLES_REJECT	false
DROP_DEFAULT_ROUTE	DE Frankfurt
NORDVPN_COUNTRY	DE
TRANSMISSION_PEER_CONGESTION_ALGORITHM	
TRANSMISSION_RPC_HOST_WHITELIST	
TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME	
UFW_EXTRA_PORTS	
HEALTH_CHECK_HOST	google.com`

**Expected behavior**
I think its supposed to just start up and have a portal right? the status stays in health check mode but the logs say all is fine.
`
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.

STARTING TINYPROXY
Found config file /etc/tinyproxy.conf, updating settings.
Setting tinyproxy port to 8888
Starting tinyproxy: tinyproxy.

Tinyproxy startup script complete.
Fri Apr  5 23:16:09 2019 /sbin/ip route add 185.0.1.224/32 via 172.17.0.1
Fri Apr  5 23:16:09 2019 /sbin/ip route add 0.0.0.0/1 via 10.8.2.1
Fri Apr  5 23:16:09 2019 /sbin/ip route add 128.0.0.0/1 via 10.8.2.1
Fri Apr  5 23:16:09 2019 Initialization Sequence Completed`

**Screenshots**
If applicable, add screenshots and/or .gif to help explain your problem.

**When does this occur?**
starting the container

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [18.04]
  * Plexguide Version: 8.5.8 [Stable]
  * Plexguide Edition: [Gdrive]
  * Plexguide Mount System: [PGBlitz]
  * Using Traefik: [Yes]
  * Domain DNS Provider:[GoDaddy]

**Comment by Admin9705** [comment]
can you post this to the forum?
