### ISSUE TITLE
Docker Stop Working

### ISSUE THREAD

**Issue by haxcop** [PGBlitz/PGBlitz.com#874]
**Describe the bug**
After changing the download path, 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Ubuntu 18 tls server 
pgblitz 8.6.1

**Comment by Admin9705** [comment]
this has nothing to do with docker running.  Your running into an issue where docker does not work.  I run UB 18 LTS and no issues.  Closing because it's offbeat, but good report still never the less.
