### ISSUE TITLE
Spelling error, Deploy GCE

### ISSUE THREAD

**Issue by Davst** [PGBlitz/PGBlitz.com#875]
**Describe the bug**
Spelling error in script to deploy GCE

**To Reproduce**
1. Deploy GCE Server

**Expected behavior**
Should say 'Assigned'

**Screenshots**
```

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🚀 Finalizing - Assinged IP Address to Instance
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

```
  * Operating System: Ubuntu18.04
  * Plexguide Version: 8.5.8

**Comment by Admin9705** [comment]
haha, good catch.  I'll fix. you'll find them here and there :D

**Comment by gunnaraas** [comment]
Opened pull request fixing this issue on PGBlitz/BlitzGCE
https://github.com/PGBlitz/BlitzGCE/pull/1

**Comment by MrDoobPG** [comment]
done merged
