### ISSUE TITLE
Change the Processing Disk Failure

### ISSUE THREAD

**Issue by haxcop** [PGBlitz/PGBlitz.com#876]
**Describe the bug**
with the latest version and beta - seems to be missing a file to accept and process the option to a second path / hd to process the files.

**To Reproduce**
Do You Want To Change the Processing Disk?

[1] No
[2] Yes

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
↘️   Type a Number | Press [ENTER]: 2

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🍖  NOM NOM: Selected to Change the Processing Path
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🌵  Current Processing Disk : /mnt

☑️   Type the path as show in the examples below! PG will then attempt
to see if your path exists!

Examples:
/mnt/mymedia
/secondhd/media
/myhd/storage/media

STOP the Process by Typing >>> exit
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
↘️   Type the NEW PATH (Follow Above Examples): /mnt/hgfs/drivepool

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅️ WOOT WOOT: The Input is Valid!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🍖  NOM NOM: Checking the Processing Path's Existance
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅️   WOOT WOOT: Location Is Valid - /mnt/hgfs/drivepool
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⌛  STANDBY: Setting Up Your Permissions
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⌛  STANDBY: Making Folders & Rebuilding the Systems Docker Containers!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR! the playbook: /opt/plexguide/menu/installer/main.yml could not be found

**Expected behavior**
no missing files 

**Screenshots**
If applicable, add screenshots and/or .gif to help explain your problem.

**What is affected by this bug?**
processing disk option
**When does this occur?**

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [18.04]
  * Plexguide Version: 8.6.1 [Stable/Beta]
  * Plexguide Server Type: [VM/local]
  * Plexguide Edition: [Gdrive]
  * Plexguide Mount System: [PGBlitz/ST2]
  * Using Traefik: [No]
  * Domain DNS Provider:[N/A]

**Logs**
If applicable provide the output from relevant logs and/or the output from the `pglog` command

**Additional context**
Detailed explanation, related issues, suggestions how to fix, links for us to have context

**Comment by Admin9705** [comment]
i'll check into it!

**Comment by haxcop** [comment]
thaks

**Comment by haxcop** [comment]
@Admin9705 
This is a VM with a shared folder from VMWARE Workstation pro 12 - the Main Host is in Windows 10

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 75] Value too large for defined data type: '/mnt/hgfs/drivepool/move'
failed: [127.0.0.1] (item=move) => {"changed": false, "item": "move", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1556549118.93-273775009034102/AnsiballZ_file.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1556549118.93-273775009034102/AnsiballZ_file.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1556549118.93-273775009034102/AnsiballZ_file.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_file_payload_8UiCTI/__main__.py\", line 885, in <module>\n  File \"/tmp/ansible_file_payload_8UiCTI/__main__.py\", line 871, in main\n  File \"/tmp/ansible_file_payload_8UiCTI/__main__.py\", line 590, in ensure_directory\n  File \"/tmp/ansible_file_payload_8UiCTI/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 1547, in set_fs_attributes_if_different\n  File \"/tmp/ansible_file_payload_8UiCTI/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 1314, in set_mode_if_different\nOSError: [Errno 75] Value too large for defined data type: '/mnt/hgfs/drivepool/move'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 75] Value too large for defined data type: '/mnt/hgfs/drivepool/downloads'
failed: [127.0.0.1] (item=downloads) => {"changed": false, "item": "downloads", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1556549119.09-2798240595620/AnsiballZ_file.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1556549119.09-2798240595620/AnsiballZ_file.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1556549119.09-2798240595620/AnsiballZ_file.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_file_payload_D4JhIT/__main__.py\", line 885, in <module>\n  File \"/tmp/ansible_file_payload_D4JhIT/__main__.py\", line 871, in main\n  File \"/tmp/ansible_file_payload_D4JhIT/__main__.py\", line 590, in ensure_directory\n  File \"/tmp/ansible_file_payload_D4JhIT/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 1547, in set_fs_attributes_if_different\n  File \"/tmp/ansible_file_payload_D4JhIT/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 1314, in set_mode_if_different\nOSError: [Errno 75] Value too large for defined data type: '/mnt/hgfs/drivepool/downloads'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 75] Value too large for defined data type: '/mnt/hgfs/drivepool/incomplete'
failed: [127.0.0.1] (item=incomplete) => {"changed": false, "item": "incomplete", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1556549119.23-24959903083048/AnsiballZ_file.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1556549119.23-24959903083048/AnsiballZ_file.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1556549119.23-24959903083048/AnsiballZ_file.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_file_payload__5884X/__main__.py\", line 885, in <module>\n  File \"/tmp/ansible_file_payload__5884X/__main__.py\", line 871, in main\n  File \"/tmp/ansible_file_payload__5884X/__main__.py\", line 590, in ensure_directory\n  File \"/tmp/ansible_file_payload__5884X/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 1547, in set_fs_attributes_if_different\n  File \"/tmp/ansible_file_payload__5884X/ansible_file_payload.zip/ansible/module_utils/basic.py\", line 1314, in set_mode_if_different\nOSError: [Errno 75] Value too large for defined data type: '/mnt/hgfs/drivepool/incomplete'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

**Comment by haxcop** [comment]
@Admin9705 any work on this?

**Comment by LooseSeal2** [comment]
This should be fixed on the latest

**Comment by lumnikemel** [comment]
I have this exact error, and my setup is very similar to OP's.
Version: 8.7.5.
VBox VM: Ubuntu 18.04
